export interface ManagerPromptCategory {
  id: string;
  label: string;
  /** Analytics sections that best support this category */
  sections: string[];
  prompts: string[];
}

/** One-click dashboard AI commands */
export const DASHBOARD_AI_COMMANDS = [
  {
    id: "daily_briefing",
    label: "Daily Briefing",
    question:
      "Give me today's sales, labor, inventory, staffing, and guest service summary.",
  },
  {
    id: "find_problems",
    label: "Find Problems",
    question: "Scan the restaurant and tell me what needs attention.",
  },
  {
    id: "improve_profit",
    label: "Improve Profit",
    question: "Show me the fastest ways to improve profit this week.",
  },
  {
    id: "build_schedule",
    label: "Build Schedule",
    question:
      "Create the best schedule based on sales forecast and employee availability.",
  },
  {
    id: "order_inventory",
    label: "Order Inventory",
    question:
      "Create a suggested order based on current inventory, sales trends, and upcoming demand.",
  },
  {
    id: "reduce_waste",
    label: "Reduce Waste",
    question: "Show me where we are wasting food or money.",
  },
  {
    id: "coach_employees",
    label: "Coach Employees",
    question: "Tell me which employees need coaching and why.",
  },
  {
    id: "boost_sales",
    label: "Boost Sales",
    question:
      "Give me sales ideas, menu promotions, and upsell suggestions for today.",
  },
  {
    id: "prepare_rush",
    label: "Prepare for Rush",
    question:
      "Tell me what to prep, who to assign, and what risks to watch before rush.",
  },
  {
    id: "owner_report",
    label: "Owner Report",
    question:
      "Give me a simple owner-level report showing sales, labor, food cost, profit, problems, and recommendations.",
  },
] as const;

export type DashboardCommandId = (typeof DASHBOARD_AI_COMMANDS)[number]["id"];

export const MANAGER_PROMPT_CATEGORIES: ManagerPromptCategory[] = [
  {
    id: "daily_overview",
    label: "Daily Manager Overview",
    sections: ["executive", "operations", "labor"],
    prompts: [
      "What should I focus on first today?",
      "What are the biggest issues in the restaurant right now?",
      "Give me a daily manager briefing.",
      "What changed since yesterday?",
      "What areas are underperforming today?",
      "What needs my attention before lunch rush?",
      "What needs my attention before dinner rush?",
      "What tasks are overdue?",
      "What should I delegate today?",
      "What risks should I watch for today?",
    ],
  },
  {
    id: "sales_revenue",
    label: "Sales & Revenue",
    sections: ["sales", "menuEngineering"],
    prompts: [
      "How are sales today compared to yesterday?",
      "How are sales today compared to this day last week?",
      "What are my best-selling menu items this week?",
      "What are my worst-selling menu items?",
      "Which items make the most profit?",
      "Which items are selling well but have low profit?",
      "What menu items should I promote today?",
      "What discounts are hurting profit?",
      "What time of day brings in the most revenue?",
      "What day of the week is usually strongest?",
      "What day of the week is usually weakest?",
      "Why were sales down yesterday?",
      "What sales trends should I know about?",
      "What is my average ticket size?",
      "How can I increase average ticket size?",
      "Which servers sell the most add-ons?",
      "Which menu category brings in the most revenue?",
      "What is my projected revenue for this week?",
      "What is my projected revenue for this month?",
      "Are we on pace to hit our sales goal?",
    ],
  },
  {
    id: "profit_cost",
    label: "Profit & Cost Control",
    sections: ["profitability", "foodCost", "labor"],
    prompts: [
      "What is my estimated profit today?",
      "What expenses are too high right now?",
      "Where are we losing money?",
      "What is our food cost percentage?",
      "What is our labor cost percentage?",
      "What is our prime cost?",
      "Is our food cost too high for our sales?",
      "Is our labor cost too high for today's volume?",
      "What can we cut without hurting service?",
      "Which menu items have the worst margin?",
      "Which vendors are costing us the most?",
      "Are prices increasing on any ingredients?",
      "Should we raise prices on any menu items?",
      "What price should this menu item be?",
      "How much profit did we make this week?",
      "What are our top controllable costs?",
      "What are our biggest profit leaks?",
      "What should I change to improve margins?",
      "What is my break-even point?",
      "How many sales do we need today to be profitable?",
    ],
  },
  {
    id: "inventory",
    label: "Inventory",
    sections: ["foodCost", "forecasting"],
    prompts: [
      "What inventory is running low?",
      "What do I need to order today?",
      "What items are overstocked?",
      "What items are close to expiring?",
      "What ingredients are being wasted the most?",
      "What ingredients are used the fastest?",
      "What do we use the most during weekends?",
      "How much inventory should I keep on hand?",
      "What should I order based on upcoming sales forecasts?",
      "Did we use more inventory than expected?",
      "Is there possible theft or waste in inventory?",
      "What items have unusual usage?",
      "What ingredients are shared across multiple menu items?",
      "What should I prep more of today?",
      "What should I prep less of today?",
      "What inventory mistakes happened this week?",
      "What are my highest-cost ingredients?",
      "What items should I remove because ingredients are too expensive?",
      "What is my current inventory value?",
      "What is my estimated waste cost this week?",
    ],
  },
  {
    id: "ordering_vendors",
    label: "Ordering & Vendors",
    sections: ["purchasing", "foodCost"],
    prompts: [
      "What vendor should I order from today?",
      "Which vendor has the best price on this item?",
      "Are any vendor prices increasing?",
      "Which vendor has been late recently?",
      "Which vendor has the most order issues?",
      "What should be included in today's purchase order?",
      "Did we receive everything we ordered?",
      "Are we missing anything from the last delivery?",
      "Did vendor pricing match the invoice?",
      "Did the three-way match pass for my last delivery?",
      "Was I short-shipped but still charged on an invoice?",
      "What invoices should I hold payment on?",
      "Compare PO vs receiving vs invoice for discrepancies",
      "Which POs are still pending delivery?",
      "Which purchase orders have been received?",
      "Has PO-DEMO-1001 been paid yet?",
      "What is the payment status on my open POs?",
      "Which vendor is costing us the most money?",
      "What items should I negotiate pricing on?",
      "What should I order before the weekend?",
      "Can you create an order list for me?",
      "Can you compare this invoice to my expected order?",
      "Are there duplicate charges on this invoice?",
      "What draft purchase orders are ready to approve?",
      "Which vendor wins the bid on onions this week?",
      "Build my purchase orders by vendor automatically",
      "Compare Sysco vs US Foods vs Gordon Food Service pricing",
      "Transmit approved POs to my vendors",
      "Scan this invoice with OCR",
      "Did any vendor quietly raise prices on my last invoice?",
      "Did cooking oil or any ingredient spike in price?",
      "Are we paying for heavy boxes on catch-weight items?",
      "Compare billed weight vs received weight on brisket",
      "Were recipe costs updated after the last invoice?",
      "Snap a photo of damaged goods for a credit memo",
      "What vendor credits are still open?",
      "Is accounting sync locked on any invoices?",
      "Can the bookkeeper pay the full vendor invoice?",
      "Which vendor is most reliable?",
      "What is our fill rate from Sysco or produce vendors?",
      "Who keeps delivering late during lunch?",
      "How often does Metro substitute cheaper brands?",
      "Give me vendor scorecard data for contract renewal",
    ],
  },
  {
    id: "scheduling_labor",
    label: "Scheduling & Labor",
    sections: ["labor", "forecasting"],
    prompts: [
      "Who should work tomorrow based on forecasted sales?",
      "Are we overstaffed today?",
      "Are we understaffed today?",
      "What schedule changes should I make?",
      "Who is approaching overtime?",
      "Who has the most call-outs?",
      "Who is most reliable?",
      "Who is best for busy shifts?",
      "Who should be scheduled for training?",
      "What is the best labor schedule for Friday night?",
      "How many cooks do I need tomorrow?",
      "How many servers do I need tonight?",
      "What labor percentage are we projected to hit?",
      "Should I cut someone early?",
      "When should I bring in extra staff?",
      "Who is available to cover a shift?",
      "What shift swaps need approval?",
      "Are there any schedule conflicts?",
      "Who requested time off?",
      "What is the best schedule based on sales history?",
    ],
  },
  {
    id: "employee_performance",
    label: "Employee Performance",
    sections: ["labor", "profitability"],
    prompts: [
      "Who are my top-performing employees?",
      "Who needs coaching?",
      "Who has the best sales numbers?",
      "Who has the most customer complaints?",
      "Who gets the best customer reviews?",
      "Who has the most late clock-ins?",
      "Who has missed the most shifts?",
      "Which employees are improving?",
      "Which employees are declining in performance?",
      "Who should be considered for promotion?",
      "Who needs more training?",
      "What should I say in this employee write-up?",
      "Help me write a coaching note for an employee.",
      "Help me write a positive recognition message.",
      "What patterns do you see in employee performance?",
      "Who is best at upselling?",
      "Who has the fastest ticket times?",
      "Who works best under pressure?",
      "Who should not be scheduled together?",
      "Who should train new hires?",
    ],
  },
  {
    id: "training",
    label: "Training",
    sections: ["labor", "menuEngineering"],
    prompts: [
      "What training does this employee still need?",
      "Create a training checklist for a new server.",
      "Create a training checklist for a new cook.",
      "Create a training checklist for a new host.",
      "Create a training checklist for a new dishwasher.",
      "What should a new manager learn first?",
      "Generate a 7-day training plan for a new employee.",
      "What menu items should employees know better?",
      "Create a quiz for servers on menu knowledge.",
      "Create a quiz for kitchen staff on food safety.",
      "What training topics are overdue?",
      "Who has completed food safety training?",
      "Who needs alcohol service training?",
      "What mistakes are new employees making most often?",
      "How can I improve onboarding?",
    ],
  },
  {
    id: "customer_service",
    label: "Customer Service",
    sections: ["customerExperience", "operations"],
    prompts: [
      "What customer complaints happened today?",
      "What are customers saying in reviews?",
      "What are the most common complaints?",
      "What compliments are we getting?",
      "How should I respond to this bad review?",
      "How should I respond to this good review?",
      "What service issues keep repeating?",
      "Which shift has the most complaints?",
      "Which employee is mentioned most in reviews?",
      "What can we do to improve guest experience?",
      "Are wait times too long?",
      "Are ticket times hurting customer satisfaction?",
      "What caused this customer issue?",
      "Write a professional apology to a customer.",
      "What should I offer this unhappy guest?",
      "What are customers asking for that we do not offer?",
      "What menu items get the best feedback?",
      "What menu items get the worst feedback?",
      "What should we improve this week?",
      "What are our review trends?",
    ],
  },
  {
    id: "kitchen_operations",
    label: "Kitchen Operations",
    sections: ["operations", "foodCost"],
    prompts: [
      "What are kitchen ticket times today?",
      "Which station is slowing down the kitchen?",
      "What menu items take the longest to make?",
      "What items are causing bottlenecks?",
      "What should we prep before dinner?",
      "Are cooks keeping up with demand?",
      "What items are being remade too often?",
      "What items are getting sent back?",
      "Why are ticket times high today?",
      "How can we speed up the kitchen?",
      "What kitchen equipment needs maintenance?",
      "What kitchen tasks are overdue?",
      "What cleaning tasks need to be completed?",
      "Are food safety logs complete?",
      "What station needs the most help?",
      "What should the kitchen focus on before rush?",
      "Are we running out of prepped items?",
      "What should be 86'd today?",
      "What items should we push today?",
      "What caused kitchen waste this week?",
    ],
  },
  {
    id: "front_of_house",
    label: "Front of House",
    sections: ["sales", "labor", "operations"],
    prompts: [
      "How long are guests waiting to be seated?",
      "Are tables turning fast enough?",
      "What is our average table turn time?",
      "Which servers have the fastest table turns?",
      "Which servers have the highest check averages?",
      "Are sections balanced fairly?",
      "Who should take large parties?",
      "Are reservations causing staffing issues?",
      "What time will we be busiest tonight?",
      "How many hosts do we need tonight?",
      "Are guests waiting too long for drinks?",
      "Are guests waiting too long for food?",
      "What FOH tasks are overdue?",
      "What should servers focus on tonight?",
      "What should hosts focus on tonight?",
      "What should bartenders focus on tonight?",
      "What guest complaints involve FOH?",
      "How can we improve table flow?",
      "Should we open another section?",
      "Should we close a section?",
    ],
  },
  {
    id: "bar_management",
    label: "Bar Management",
    sections: ["menuEngineering", "inventory"],
    prompts: [
      "What liquor is running low?",
      "What beer is selling fastest?",
      "What cocktails are most profitable?",
      "What drinks are not selling?",
      "What bar items should I order?",
      "Are pours costing too much?",
      "Is there possible overpouring?",
      "What is our bar cost percentage?",
      "What drinks should we feature this weekend?",
      "What cocktail has the best margin?",
      "What alcohol inventory has unusual usage?",
      "Which bartender has the highest sales?",
      "Which bartender has the most voids/comps?",
      "What drinks should we remove from the menu?",
      "What seasonal drinks should we add?",
    ],
  },
  {
    id: "menu_management",
    label: "Menu Management",
    sections: ["menuEngineering", "profitability"],
    prompts: [
      "What menu items should we remove?",
      "What menu items should we promote?",
      "What menu items should we reprice?",
      "What dishes have the best profit margin?",
      "What dishes have the worst profit margin?",
      "What items are popular but expensive to make?",
      "What items are cheap to make but sell well?",
      "What menu items use ingredients that often go bad?",
      "What should our special be today?",
      "Create a weekly special using inventory we already have.",
      "What menu item should we test next?",
      "What items should be bundled together?",
      "What upsells should servers suggest?",
      "What side items are most profitable?",
      "What desserts sell best?",
      "What menu items are slowing down the kitchen?",
      "What items get the most complaints?",
      "What items get the best reviews?",
      "What seasonal menu changes should we make?",
      "Create a limited-time offer.",
    ],
  },
  {
    id: "marketing",
    label: "Marketing",
    sections: ["marketing", "externalFactors"],
    prompts: [
      "What should we post on Facebook today?",
      "What should we post on Instagram today?",
      "Create a social media post for today's special.",
      "Create a promotion for a slow Tuesday.",
      "What offer would bring in more lunch customers?",
      "What offer would bring in more dinner customers?",
      "What promotion should we run this weekend?",
      "What customers should we target this week?",
      "What menu item should we advertise?",
      "Write an email campaign for regular customers.",
      "Write a text message promo for tonight.",
      "Create a loyalty offer.",
      "What events should we promote around?",
      "What local businesses should we partner with?",
      "What is a good happy hour idea?",
      "What marketing worked best last month?",
      "What promotion had the best return?",
      "What should we stop promoting?",
      "Create a marketing calendar for next month.",
      "Give me 10 ad ideas for this restaurant.",
    ],
  },
  {
    id: "online_delivery",
    label: "Online Orders & Delivery",
    sections: ["sales", "profitability", "operations"],
    prompts: [
      "How many online orders came in today?",
      "What items sell best online?",
      "What items are bad for delivery?",
      "Are delivery orders profitable?",
      "Which delivery platform costs us the most?",
      "What are our delivery fees costing us?",
      "Are online order times too long?",
      "What items are often missing from orders?",
      "What customer complaints involve delivery?",
      "Should we turn off delivery during rush?",
      "What delivery menu items should we remove?",
      "What online-only special should we run?",
      "Are third-party orders hurting kitchen flow?",
      "Which platform brings the most revenue?",
      "Which platform brings the most profit?",
    ],
  },
  {
    id: "reservations_events",
    label: "Reservations & Events",
    sections: ["forecasting", "marketing"],
    prompts: [
      "How many reservations do we have tonight?",
      "Are we prepared for large parties?",
      "What events are coming up?",
      "Do we need extra staff for this event?",
      "What should we prep for tomorrow's event?",
      "What is the expected revenue from this event?",
      "Create a banquet checklist.",
      "Create a catering prep list.",
      "What catering orders are due this week?",
      "What should we charge for this catering order?",
      "What items work best for catering?",
      "What events should we market?",
      "Are deposits collected for upcoming events?",
      "What private event tasks are incomplete?",
      "Create a follow-up email for an event customer.",
    ],
  },
  {
    id: "cleaning_maintenance",
    label: "Cleaning & Maintenance",
    sections: ["operations"],
    prompts: [
      "What cleaning tasks are due today?",
      "What cleaning tasks are overdue?",
      "Who was assigned to cleaning today?",
      "What equipment needs maintenance?",
      "What maintenance issues were reported?",
      "What repairs are urgent?",
      "What repairs can wait?",
      "Is the walk-in cooler temperature safe?",
      "Are temperature logs complete?",
      "What safety checks are missing?",
      "What should be cleaned before inspection?",
      "Create a closing cleaning checklist.",
      "Create an opening checklist.",
      "Create a weekly deep-cleaning schedule.",
      "What areas are being missed most often?",
    ],
  },
  {
    id: "compliance_safety",
    label: "Compliance & Safety",
    sections: ["operations", "customerExperience"],
    prompts: [
      "Are food safety logs complete?",
      "Are employee certifications up to date?",
      "Who needs a food handler card renewal?",
      "Who needs alcohol certification renewal?",
      "Are temperatures being logged correctly?",
      "Are there any health inspection risks?",
      "What should we fix before inspection?",
      "What safety incidents happened this week?",
      "Are accident reports complete?",
      "What allergen risks should staff know?",
      "Create an allergen guide for staff.",
      "What menu items contain dairy?",
      "What menu items contain gluten?",
      "What menu items contain nuts?",
      "What menu items are safe for vegetarian guests?",
      "Are we following labor rules for minors?",
      "Are breaks being taken correctly?",
      "Are overtime rules being followed?",
      "What compliance tasks are overdue?",
      "Create a health inspection prep checklist.",
    ],
  },
  {
    id: "cash_payments",
    label: "Cash, Payments & Accounting",
    sections: ["profitability", "operations"],
    prompts: [
      "Did the cash drawer balance?",
      "Were there any cash shortages?",
      "Were there any cash overages?",
      "Who closed the drawer last night?",
      "What refunds were issued today?",
      "What voids happened today?",
      "What comps happened today?",
      "Are voids unusually high?",
      "Are discounts unusually high?",
      "Are refunds unusually high?",
      "What payment issues happened today?",
      "What deposits need to be made?",
      "Did sales match payment totals?",
      "What invoices are due soon?",
      "What bills need to be paid?",
      "What expenses were added this week?",
      "What is our cash flow looking like?",
      "Are we profitable this month?",
      "What expenses increased this month?",
      "Create a weekly financial summary.",
    ],
  },
  {
    id: "theft_waste",
    label: "Theft, Waste & Loss Prevention",
    sections: ["operations", "foodCost", "profitability"],
    prompts: [
      "Are there signs of employee theft?",
      "Are voids higher than normal?",
      "Are comps higher than normal?",
      "Are refunds higher than normal?",
      "Is inventory usage higher than sales justify?",
      "Which items are disappearing faster than expected?",
      "Are discounts being abused?",
      "Are cash shortages recurring?",
      "Which employees have unusual transaction patterns?",
      "What should I audit today?",
      "Are there unusual clock-in patterns?",
      "Are employees clocking in too early?",
      "Are employees staying clocked in too long?",
      "Are waste logs accurate?",
      "What losses happened this week?",
    ],
  },
  {
    id: "forecasting",
    label: "Forecasting",
    sections: ["forecasting", "externalFactors"],
    prompts: [
      "How busy will we be tomorrow?",
      "How busy will we be this weekend?",
      "How much staff do I need next Friday?",
      "What should I order for next week?",
      "What ingredients will we likely run out of?",
      "What sales should we expect next month?",
      "What labor should we schedule next week?",
      "What menu items will sell most this weekend?",
      "What weather could affect sales?",
      "What local events could affect sales?",
      "What holidays are coming up that affect business?",
      "What should we prep based on forecasted demand?",
      "What is the expected lunch rush tomorrow?",
      "What is the expected dinner rush tomorrow?",
      "Are we prepared for the forecasted volume?",
    ],
  },
  {
    id: "owner_level",
    label: "Owner-Level Questions",
    sections: ["executive", "profitability", "marketing"],
    prompts: [
      "How is the restaurant performing overall?",
      "What are the biggest problems in the business?",
      "What would you fix first if you owned this restaurant?",
      "What is hurting profitability the most?",
      "What are our best growth opportunities?",
      "What should we invest in next?",
      "Should we add another location?",
      "Should we expand catering?",
      "Should we change hours?",
      "Should we close on slow days?",
      "Should we open earlier?",
      "Should we stay open later?",
      "What are the top 5 decisions I need to make this month?",
      "What KPIs should I watch daily?",
      "What KPIs should I watch weekly?",
      "What KPIs should I watch monthly?",
      "Create an owner report.",
      "Create a manager report.",
      "Create an investor-style report.",
      "What is the health score of my restaurant?",
    ],
  },
  {
    id: "ai_commands",
    label: "AI Assistant Commands",
    sections: ["executive"],
    prompts: [
      "Summarize the restaurant in one paragraph.",
      "Give me a red/yellow/green status report.",
      "Give me a to-do list for today.",
      "Create a manager checklist for this shift.",
      "Create a closing checklist based on today's issues.",
      "Create an opening checklist for tomorrow.",
      "Tell me what changed this week.",
      "Tell me what looks unusual.",
      "Tell me what I am missing.",
      "Tell me what could become a problem soon.",
    ],
  },
];

export const ALL_MANAGER_PROMPTS = MANAGER_PROMPT_CATEGORIES.flatMap((cat) =>
  cat.prompts.map((question) => ({
    categoryId: cat.id,
    categoryLabel: cat.label,
    question,
    sections: cat.sections,
  }))
);

export function getCategoryById(id: string) {
  return MANAGER_PROMPT_CATEGORIES.find((c) => c.id === id);
}

export function getDashboardCommand(id: string) {
  return DASHBOARD_AI_COMMANDS.find((c) => c.id === id);
}

export function matchPromptCategory(question: string): ManagerPromptCategory | undefined {
  const q = question.toLowerCase();
  return MANAGER_PROMPT_CATEGORIES.find((cat) =>
    cat.prompts.some((p) => p.toLowerCase() === q)
  ) ?? MANAGER_PROMPT_CATEGORIES.find((cat) =>
    cat.prompts.some((p) => q.includes(p.toLowerCase().slice(0, 24)))
  );
}

export function searchPrompts(query: string, limit = 20) {
  const q = query.toLowerCase().trim();
  if (!q) return ALL_MANAGER_PROMPTS.slice(0, limit);
  return ALL_MANAGER_PROMPTS.filter(
    (p) =>
      p.question.toLowerCase().includes(q) ||
      p.categoryLabel.toLowerCase().includes(q)
  ).slice(0, limit);
}
