import type { ReportConfig, ReportDefinition } from "@/lib/reports/types";

const col = (
  id: string,
  label: string,
  type: ReportDefinition["columns"][0]["type"] = "text",
  defaultVisible = true
) => ({ id, label, type, defaultVisible });

export const REPORT_REGISTRY: ReportDefinition[] = [
  {
    id: "sales-by-item",
    label: "Sales by menu item",
    category: "Analytics",
    description: "Revenue and quantity sold per menu item.",
    permission: "view_analytics",
    columns: [
      col("name", "Item"),
      col("quantity", "Qty sold", "number"),
      col("sales", "Revenue", "currency"),
    ],
    defaultSort: { column: "sales", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "sales-by-category",
    label: "Sales by category",
    category: "Analytics",
    description: "Revenue grouped by menu category.",
    permission: "view_analytics",
    columns: [
      col("category", "Category"),
      col("quantity", "Qty sold", "number"),
      col("sales", "Revenue", "currency"),
    ],
    defaultSort: { column: "sales", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "sales-by-daypart",
    label: "Sales by daypart",
    category: "Analytics",
    description: "Breakfast, lunch, dinner, and late-night performance.",
    permission: "view_analytics",
    columns: [
      col("daypart", "Daypart"),
      col("orders", "Orders", "number"),
      col("sales", "Revenue", "currency"),
    ],
    defaultSort: { column: "sales", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "sales-by-channel",
    label: "Sales by channel",
    category: "Analytics",
    description: "Dine-in, delivery, and other channel breakdown.",
    permission: "view_analytics",
    columns: [
      col("channel", "Channel"),
      col("orders", "Orders", "number"),
      col("sales", "Revenue", "currency"),
      col("profit", "Profit", "currency"),
      col("marginPct", "Margin %", "percent"),
    ],
    defaultSort: { column: "sales", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "menu-engineering",
    label: "Menu engineering matrix",
    category: "Analytics",
    description: "Stars, plowhorses, puzzles, and dogs by margin and popularity.",
    permission: "view_analytics",
    columns: [
      col("name", "Item"),
      col("quadrant", "Quadrant", "badge"),
      col("sales", "Revenue", "currency"),
      col("marginPct", "Margin %", "percent"),
      col("popularityPct", "Popularity %", "percent"),
      col("contribution", "Contribution", "currency"),
    ],
    defaultSort: { column: "contribution", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "labor-by-employee",
    label: "Labor by employee",
    category: "Analytics",
    description: "Scheduled vs actual hours and labor cost per employee.",
    permission: "view_analytics",
    columns: [
      col("name", "Employee"),
      col("role", "Role"),
      col("scheduledHours", "Scheduled hrs", "number"),
      col("actualHours", "Actual hrs", "number"),
      col("overtimeHours", "OT hrs", "number"),
      col("laborCost", "Labor cost", "currency"),
      col("laborPct", "Labor %", "percent"),
    ],
    defaultSort: { column: "laborCost", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "profit-by-employee",
    label: "Profit by employee",
    category: "Analytics",
    description: "Sales and profit attributed to each team member.",
    permission: "view_analytics",
    columns: [
      col("name", "Employee"),
      col("role", "Role"),
      col("sales", "Sales", "currency"),
      col("profit", "Profit", "currency"),
      col("marginPct", "Margin %", "percent"),
    ],
    defaultSort: { column: "profit", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "avt-variance",
    label: "Actual vs theoretical variance",
    category: "Back Office",
    description: "Ingredient usage variance with cost impact and likely causes.",
    permission: "view_analytics",
    columns: [
      col("name", "Ingredient"),
      col("unit", "Unit"),
      col("theoreticalQty", "Theoretical", "number"),
      col("actualQty", "Actual", "number"),
      col("varianceQty", "Variance", "number"),
      col("variancePct", "Variance %", "percent"),
      col("varianceCost", "Cost impact", "currency"),
      col("flag", "Flag", "badge"),
      col("likelyCause", "Likely cause", "text", false),
    ],
    defaultSort: { column: "varianceCost", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "waste-log",
    label: "Waste & spoilage log",
    category: "Back Office",
    description: "Recent waste entries by item, reason, and cost.",
    permission: "view_analytics",
    columns: [
      col("date", "Date", "date"),
      col("item", "Item"),
      col("quantity", "Qty", "number"),
      col("unit", "Unit"),
      col("reason", "Reason"),
      col("cost", "Cost", "currency"),
      col("employee", "Recorded by", "text", false),
      col("shift", "Shift", "text", false),
    ],
    defaultSort: { column: "date", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "monthly-variance",
    label: "Monthly count variance",
    category: "Inventory",
    description: "Theoretical vs actual from the latest monthly count.",
    permission: "manage_inventory",
    columns: [
      col("name", "Item"),
      col("unit", "Unit"),
      col("openingQty", "Opening", "number"),
      col("purchasesQty", "Purchases", "number"),
      col("theoreticalQty", "Theoretical", "number"),
      col("actualQty", "Actual", "number"),
      col("varianceQty", "Variance", "number"),
      col("variancePct", "Variance %", "percent"),
      col("varianceCost", "Cost impact", "currency"),
      col("flag", "Flag", "badge"),
    ],
    defaultSort: { column: "varianceCost", direction: "desc" },
  },
  {
    id: "inventory-on-hand",
    label: "Inventory on hand",
    category: "Inventory",
    description: "Current stock levels, par, and value.",
    permission: "manage_inventory",
    columns: [
      col("name", "Item"),
      col("category", "Storage zone"),
      col("quantity", "On hand", "number"),
      col("unit", "Unit"),
      col("minQuantity", "Par/min", "number"),
      col("costPerUnit", "Unit cost", "currency"),
      col("value", "Value", "currency"),
      col("supplier", "Supplier", "text", false),
      col("barcode", "Barcode", "text", false),
    ],
    defaultSort: { column: "name", direction: "asc" },
  },
  {
    id: "low-stock",
    label: "Low stock alert",
    category: "Inventory",
    description: "Items at or below minimum quantity.",
    permission: "manage_inventory",
    columns: [
      col("name", "Item"),
      col("quantity", "On hand", "number"),
      col("minQuantity", "Minimum", "number"),
      col("unit", "Unit"),
      col("supplier", "Supplier"),
      col("shortfall", "Shortfall", "number"),
    ],
    defaultSort: { column: "shortfall", direction: "desc" },
  },
  {
    id: "expenses",
    label: "Expense ledger",
    category: "Finances",
    description: "All expenses with category and receipt links.",
    permission: "view_finances",
    columns: [
      col("date", "Date", "date"),
      col("description", "Description"),
      col("category", "Category"),
      col("amount", "Amount", "currency"),
      col("vendor", "Vendor", "text", false),
    ],
    defaultSort: { column: "date", direction: "desc" },
    defaultFilters: { days: 30 },
  },
  {
    id: "payroll-preview",
    label: "Payroll preview",
    category: "Payroll",
    description: "Hours, pay, tips, and gross by employee for a pay period.",
    permission: "manage_payroll",
    columns: [
      col("name", "Employee"),
      col("role", "Role"),
      col("regHours", "Reg hrs", "number"),
      col("otHours", "OT hrs", "number"),
      col("basePay", "Base pay", "currency"),
      col("otPay", "OT pay", "currency"),
      col("tips", "Tips", "currency"),
      col("gross", "Gross", "currency"),
    ],
    defaultSort: { column: "gross", direction: "desc" },
    defaultFilters: { days: 14 },
  },
  {
    id: "compliance-incidents",
    label: "Compliance incidents",
    category: "Compliance",
    description: "OSHA and workplace incident log.",
    permission: "manage_compliance",
    columns: [
      col("reportedAt", "Reported", "date"),
      col("incidentType", "Type"),
      col("category", "Category"),
      col("description", "Description"),
      col("severity", "Severity", "badge"),
      col("status", "Status", "badge"),
      col("oshaRecordable", "OSHA recordable"),
      col("staffName", "Staff", "text", false),
    ],
    defaultSort: { column: "reportedAt", direction: "desc" },
    defaultFilters: { days: 90 },
  },
  {
    id: "staff-turnover",
    label: "Staff turnover",
    category: "Staff",
    description: "Departures, tenure, and turnover rate by role.",
    permission: "manage_retention",
    columns: [
      col("role", "Role"),
      col("activeStaff", "Active", "number"),
      col("departures", "Departures", "number"),
      col("turnoverRate", "Turnover %", "percent"),
      col("avgTenure", "Avg tenure (mo)", "number"),
    ],
    defaultSort: { column: "turnoverRate", direction: "desc" },
    defaultFilters: { months: 12 },
  },
  {
    id: "vendor-scorecards",
    label: "Vendor scorecards",
    category: "Purchasing",
    description: "Fill rate, on-time delivery, and reliability grades.",
    permission: "view_analytics",
    columns: [
      col("vendor", "Vendor"),
      col("fillRatePct", "Fill rate %", "percent"),
      col("onTimePct", "On-time %", "percent"),
      col("substitutionRatePct", "Substitution %", "percent"),
      col("reliabilityGrade", "Grade", "badge"),
      col("reliabilityScore", "Score", "number"),
      col("deliveryCount", "Deliveries", "number"),
    ],
    defaultSort: { column: "reliabilityScore", direction: "desc" },
    defaultFilters: { days: 90 },
  },
  {
    id: "log-book-entries",
    label: "Manager log book",
    category: "Operations",
    description: "Daily log entries with notes and metrics.",
    permission: "view_log_book",
    columns: [
      col("date", "Date", "date"),
      col("category", "Category"),
      col("title", "Title"),
      col("content", "Notes"),
      col("salesTotal", "Sales", "currency", false),
      col("guestCount", "Guests", "number", false),
      col("laborHours", "Labor hrs", "number", false),
    ],
    defaultSort: { column: "date", direction: "desc" },
    defaultFilters: { days: 30 },
  },
];

export function getReportDefinition(reportId: string): ReportDefinition | undefined {
  return REPORT_REGISTRY.find((r) => r.id === reportId);
}

export function defaultReportConfig(reportId: string): ReportConfig {
  const def = getReportDefinition(reportId);
  if (!def) {
    throw new Error(`Unknown report: ${reportId}`);
  }
  return {
    reportId,
    columns: def.columns.filter((c) => c.defaultVisible !== false).map((c) => c.id),
    filters: { ...def.defaultFilters },
    sort: def.defaultSort,
    branding: {
      title: def.label,
      showTimestamp: true,
      showLocation: true,
    },
    rowLimit: 100,
    visualization: "table",
  };
}

export function listReportsByCategory(): Record<string, ReportDefinition[]> {
  const grouped: Record<string, ReportDefinition[]> = {};
  for (const report of REPORT_REGISTRY) {
    if (!grouped[report.category]) grouped[report.category] = [];
    grouped[report.category].push(report);
  }
  return grouped;
}
